version: '3.8'

services:
  goapp:
    build:
      dockerfile: Dockerfile
    container_name: goapp
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8
    container_name: gomysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - sql_data:/var/lib/mysql
      - ./migrations/:/var/tmp/migrations/

volumes:
  sql_data: